# Generated by Django 2.2.4 on 2019-08-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=300)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer_url', models.CharField(blank=True, max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('lineup', models.CharField(max_length=400)),
                ('cost', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='indiepk_app.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo_url', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise', to='indiepk_app.Artist')),
            ],
        ),
    ]
