# Generated by Django 2.2.4 on 2019-08-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiepk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
